import mongoose from 'mongoose';
import Travel from '../models/Travel';
import dotenv from 'dotenv';
import { create } from 'domain';

dotenv.config();

const travels = [
  {
    title: "Barcelona Concert",
    country: "Spain",
    location: "Barcelona",
    coordinates: { lat: 41.3851, lng: 2.1734 },
    dates: {
      start: new Date("2023-07-10"),
      end: new Date("2023-07-17"),
    },
    duration: 5,
    description: "Discovering Gaudí's masterpieces and Maneskin concert.",
    type: "cultural",
    images: [],
    highlights: ["Sagrada Familia", "Park Güell", "Gothic Quarter", "Tapas in El Born"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Vino y Arquitectura en Burdeos",
    country: "France",
    location: "Burdeos",
    coordinates: { lat: 44.8378, lng: -0.5792 },
    dates: {
      start: new Date("2018-07-25"),
      end: new Date("2018-07-28"),
    },
    duration: 3,
    description: "Descubriendo los secretos del vino y la arquitectura neoclásica francesa.",
    type: "cultural",
    images: [],
    highlights: ["Tour por bodegas de Saint-Émilion", "Espejo de Agua", "Cathédrale Saint-André", "Degustación de vinos"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "London Calling",
    country: "United Kingdom",
    location: "Londres",
    coordinates: { lat: 51.5074, lng: -0.1278 },
    dates: {
      start: new Date("2018-10-05"),
      end: new Date("2018-10-09"),
    },
    duration: 4,
    description: "Paseando por la histórica ciudad con un toque de lluvia británica. ¡Cheers!",
    type: "cultural",
    images: [],
    highlights: ["London Eye", "Tower of London", "British Museum", "Piccadilly Circus", "Tea Time"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Magia Marroquí en Marrakech",
    country: "Morocco",
    location: "Marrakech",
    coordinates: { lat: 31.6295, lng: -7.9811 },
    dates: {
      start: new Date("2019-04-15"),
      end: new Date("2019-04-20"),
    },
    duration: 5,
    description: "Perdiéndose en los zocos y respirando la esencia del norte de África.",
    type: "adventure",
    images: [],
    highlights: ["Jemaa el-Fnaa", "Jardines Majorelle", "Palacio Bahía", "Té de menta en terraza"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Castillos y Whisky en Edimburgo",
    country: "United Kingdom",
    location: "Edimburgo",
    coordinates: { lat: 55.9533, lng: -3.1883 },
    dates: {
      start: new Date("2019-09-17"),
      end: new Date("2019-09-21"),
    },
    duration: 4,
    description: "Explorando la ciudad medieval con un buen whisky en la mano.",
    type: "cultural",
    images: [],
    highlights: ["Edinburgh Castle", "Royal Mile", "Arthur's Seat", "Tour de whisky", "Ghost Tour"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Highlands Salvajes",
    country: "United Kingdom",
    location: "Highlands",
    coordinates: { lat: 57.1200, lng: -4.7100 },
    dates: {
      start: new Date("2019-09-20"),
      end: new Date("2019-09-20"),
    },
    duration: 1,
    description: "Un día entre paisajes épicos y leyendas celtas.",
    type: "adventure",
    images: [],
    highlights: ["Loch Ness", "Glen Coe", "Highland cows", "Paisajes cinematográficos"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "París en Invierno",
    country: "France",
    location: "París",
    coordinates: { lat: 48.8566, lng: 2.3522 },
    dates: {
      start: new Date("2022-02-17"),
      end: new Date("2022-02-22"),
    },
    duration: 5,
    description: "La ciudad luz con un toque invernal y mucho romanticismo.",
    type: "cultural",
    images: [],
    highlights: ["Torre Eiffel invernal", "Louvre", "Montmartre", "Crêpes callejeros", "Sena congelado"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Praga Gótica",
    country: "Czech Republic",
    location: "Praga",
    coordinates: { lat: 50.0755, lng: 14.4378 },
    dates: {
      start: new Date("2022-04-01"),
      end: new Date("2022-04-07"),
    },
    duration: 6,
    description: "Caminando entre puentes medievales y cervezas checas.",
    type: "cultural",
    images: [],
    highlights: ["Puente de Carlos", "Reloj Astronómico", "Castillo de Praga", "Cervecería tradicional"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Safari en Tanzania",
    country: "Tanzania",
    location: "Tanzania",
    coordinates: { lat: -6.3690, lng: 34.8888 },
    dates: {
      start: new Date("2022-11-25"),
      end: new Date("2022-11-30"),
    },
    duration: 5,
    description: "Encuentros salvajes en la sabana africana. ¡Hakuna Matata!",
    type: "adventure",
    images: [],
    highlights: ["Safari en jeep", "Big Five", "Atardeceres savana", "Cultura Masai"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Reserva Masai Mara",
    country: "Kenya",
    location: "Masai Mara",
    coordinates: { lat: -1.5810, lng: 35.1395 },
    dates: {
      start: new Date("2022-11-27"),
      end: new Date("2022-11-28"),
    },
    duration  : 1,
    description: "Dos días entre leones y cebras en la reserva más famosa. ¡Simba, aquí estamos!",
    type: "adventure",
    images: [],
    highlights: ["Gran migración", "Leones cazando", "Habitación con vista savana", "Tribu Masai"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Samburu Exótico",
    country: "Kenya",
    location: "Samburu",
    coordinates: { lat: 1.2150, lng: 36.9000 },
    dates: {
      start: new Date("2022-11-25"),
      end: new Date("2022-11-26"),
    },
    duration: 1,
    description: "Fauna única y paisajes áridos del norte de Kenia.",
    type: "adventure",
    images: [],
    highlights: ["Jirafas reticuladas", "Cebras de Grevy", "Río Ewaso Ng'iro", "Noche en lodge"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Lago Nakuru Rosa",
    country: "Kenya",
    location: "Nakuru",
    coordinates: { lat: -0.3031, lng: 36.0800 },
    dates: {
      start: new Date("2022-11-23"),
      end: new Date("2022-11-24"),
    },
    duration: 1,
    description: "Flamencos rosados hasta donde alcanza la vista.",
    type: "adventure",
    images: [],
    highlights: ["Millones de flamencos", "Rinocerontes blancos", "Lago alcalino", "Birdwatching extremo"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Maldives Paradise",
    country: "Maldives",
    location: "Malé",
    coordinates: { lat: 3.2028, lng: 73.2207 },
    dates: {
      start: new Date("2022-11-30"),
      end: new Date("2022-12-05"),
    },
    duration: 5,
    description: "Cinco días en cabañas sobre el agua con el mar turquesa.",
    type: "vacation",
    images: [],
    highlights: ["Snorkeling con rayas", "Cena en la playa", "Spa sobre el agua", "Snorkel en arrecife"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Islandia ❄️",
    country: "Iceland",
    location: "Islandia",
    coordinates: { lat: 64.9631, lng: -19.0208 },
    dates: {
      start: new Date("2023-03-23"),
      end: new Date("2023-04-04"),
    },
    duration: 12,
    description: "Aventura entre glaciares, géiseres y auroras boreales. ¡Chu helado!",
    type: "adventure",
    images: [],
    highlights: ["Aurora Boreal", "Círculo Dorado", "Baño en Blue Lagoon", "Glaciar Vatnajökull"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Puesta de Sol en Santorini",
    country: "Greece",
    location: "Santorini",
    coordinates: { lat: 36.3932, lng: 25.4615 },
    dates: {
      start: new Date("2023-10-23"),
      end: new Date("2023-10-25"),
    },
    duration: 2,
    description: "Un día en las casas blancas con vistas al volcán. ¡Chu griego!",
    type: "vacation",
    images: [],
    highlights: ["Puesta de sol en Oia", "Casas cueva", "Vino Assyrtiko", "Playas de lava"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Atenas Clásica",
    country: "Greece",
    location: "Atenas",
    coordinates: { lat: 37.9838, lng: 23.7275 },
    dates: {
      start: new Date("2023-10-19"),
      end: new Date("2023-10-23"),
    },
    duration: 4,
    description: "Siguiendo los pasos de los antiguos dioses griegos. ¡Opa, chu!",
    type: "cultural",
    images: [],
    highlights: ["Acrópolis", "Museo Arqueológico", "Plaka", "Comida callejera griega"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Onsen en Hakone",
    country: "Japan",
    location: "Hakone",
    coordinates: { lat: 35.2324, lng: 139.1063 },
    dates: {
      start: new Date("2024-03-23"),
      end: new Date("2024-03-24"),
    },
    duration: 1,
    description: "Relajación total en aguas termales con vistas al Fuji.",
    type: "vacation",
    images: [],
    highlights: ["Onsen al aire libre", "Vista Monte Fuji", "Huevos negros de Owakudani", "Paseo en barco pirata"],
    createdAt: new Date(),
    updatedAt: new Date(),
  }, 
   {
    title: "Montañas en Takayama",
    country: "Japan",
    location: "Takayama",
    coordinates: { lat: 36.1000, lng: 137.2500 },
    dates: {
      start: new Date("2024-03-25"),
      end: new Date("2024-03-27"),
    },
    duration: 2,
    description: "Visita a los pueblos tradicionales de Takayama.",
    type: "vacation",
    images: [],
    highlights: ["Pueblos tradicionales", "Arquitectura antigua", "Caminatas en montaña", "Vistas panorámicas"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Templos de Kioto",
    country: "Japan",
    location: "Kioto",
    coordinates: { lat: 35.0116, lng: 135.7681 },
    dates: {
      start: new Date("2024-03-28"),
      end: new Date("2024-03-30"),
    },
    duration: 2,
    description: "Inmersión en la cultura tradicional japonesa. ¡Kawaii chu!",
    type: "cultural",
    images: [],
    highlights: ["Fushimi Inari", "Kinkaku-ji", "Gion District", "Ceremonia del té"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Osaka Moderna",
    country: "Japan",
    location: "Osaka",
    coordinates: { lat: 34.6937, lng: 135.5023 },
    dates: {
      start: new Date("2024-03-31"),
      end: new Date("2024-04-03"),
    },
    duration: 4,
    description: "Comida callejera y luces de neón en la ciudad de la cocina. ¡Oishii chu!",
    type: "cultural",
    images: [],
    highlights: ["Dotonbori", "Castillo de Osaka", "Takoyaki callejero", "Acuario Kaiyukan"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Kioto Profundo",
    country: "Japan",
    location: "Kioto",
    coordinates: { lat: 35.0116, lng: 135.7681 },
    dates: {
      start: new Date("2024-04-04"),
      end: new Date("2024-04-09"),
    },
    duration: 5,
    description: "Segunda inmersión en la capital cultural de Japón.",
    type: "cultural",
    images: [],
    highlights: ["Arashiyama Bamboo Grove", "Kiyomizu-dera", "Mercado Nishiki", "Geisha spotting"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
   title: "San Francisco NBA",
    country: "USA",
    location: "San Francisco",
    coordinates: { lat: 37.7749, lng: -122.4194 },
    dates: {
      start: new Date("2024-10-07"),
      end: new Date("2024-10-10"),
    },
    duration: 3,
    description: "Conferencia tech y exploración urbana.",
    type: "business",
    images: [],
    highlights: ["Silicon Valley tour", "Golden Gate Bridge", "Alcatraz", "Cable car ride"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Fiesta en Las Vegas",
    country: "USA",
    location: "Las Vegas",
    coordinates: { lat: 36.1699, lng: -115.1398 },
    dates: {
      start: new Date("2024-10-11"),
      end: new Date("2024-10-13"),
    },
    duration: 2,
    description: "Luces, shows y mucho entretenimiento. ¡What happens in Vegas...!",
    type: "vacation",
    images: [],
    highlights: ["Strip de noche", "Show de cirque", "Gran Cañón tour", "Buffet extravagante"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Arizona Desértico",
    country: "USA",
    location: "Arizona",
    coordinates: { lat: 34.0489, lng: -111.0937 },
    dates: {
      start: new Date("2024-10-12"),
      end: new Date("2024-10-12"),
    },
    duration: 1,
    description: "Un día entre cactus y paisajes del lejano oeste. ¡Yeehaw!",
    type: "adventure",
    images: [],
    highlights: ["Monument Valley", "Cactus gigantes", "Puesta de sol desértica", "Foto con sombrero cowboy"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Lisboa Navideña",
    country: "Portugal",
    location: "Lisboa",
    coordinates: { lat: 38.7223, lng: -9.1393 },
    dates: {
      start: new Date("2025-12-20"),
      end: new Date("2025-12-23"),
    },
    duration: 3,
    description: "Navidad con pasteles de nata y fados en la ciudad de las siete colinas.",
    type: "cultural",
    images: [],
    highlights: ["Torre de Belém", "Pastéis de Belém", "Tranvía 28", "Miradores con vistas", "Fado en Alfama"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

const seedDatabase = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI || 'mongodb://localhost:27017/portfolio');
    console.log('✅ Conectado a MongoDB');

    // Limpiar colección
    await Travel.deleteMany({});
    console.log('🗑️  Colección limpiada');

    // Insertar datos
    await Travel.insertMany(travels);
    console.log(`🌱 Insertados ${travels.length} viajes`);

    // Mostrar estadísticas
    const count = await Travel.countDocuments();
    console.log(`📊 Total de viajes en DB: ${count}`);

    process.exit(0);
  } catch (error) {
    console.error('❌ Error:', error);
    process.exit(1);
  }
};

seedDatabase();